### ISSUE TITLE
What is the format for the `home_row_keys` config option?

### ISSUE THREAD

**Issue by Crandel** [moverest/wl-kbptr#6]
There are no `home_row_keys` format in the example. I tried this one

```toml
[general]
home_row_keys=hjkltsra
```

But got this error

```
err: Could not parse home row keys. Not enough characters.
```
